### ISSUE TITLE
support for buildx builders and containerd image store

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copa-action#32]
today, actions runs using buildkit as a container but buildkit container cannot access registry credentials
action needs to 
- support for buildx builders for private images 
- support for containerd image store for private and local images

for implementation, we can make the buildkit container optional unless user specified a specific version. otherwise, we can let copa perform it's regular fallback steps and have docs/guidance to either create a buildx builder or enable containerd image store. I think this would be a breaking change unless we can create buildx builder for the user.

**Comment by ofschnai** [comment]
Hello, Is the Copa Action in place? Can you please let me know the usage of it?

**Comment by ashnamehrotra** [comment]
@ofschnai Yes, the Copa Action now supports patching local and private images. The ways to connect the action to buildkit are documented [here](https://github.com/project-copacetic/copa-action?tab=readme-ov-file#ways-to-connect-to-buildkit)

**Comment by ofschnai** [comment]
@ashnamehrotra  Does this below step needs any authentication token?


 ```
       - name: Run Copa action 
         if: steps.vuln_count.outputs.vuln_count != '0' 
         id: copa 
         # using main for testing purposes 
         # use a tag (such as v1 or v1.0.1) at a bare minimum 
         # recommendation is to pin to a digest for security and stability 
         # and rely on dependabot for digest/version updates 
         uses: project-copacetic/copa-action@main 
         with: 
            image: ${{ matrix.images }} 
            image-report: "report.json" 
            patched-tag: "patched" 
            timeout: "5m" # optional, default is 5m 
            output: vex.json # optional 
            format: "openvex" # optional, default is openvex 
```


After using this I am getting below error -

![image](https://github.com/project-copacetic/copa-action/assets/121802270/1fe8067d-7df7-47f5-83ca-18769413bc89)
