### ISSUE TITLE
Unable to produce openvex report

### ISSUE THREAD

**Issue by R3DRUN3** [project-copacetic/copa-action#33]
We are trying to leverge the feature introduced by [this PR](https://github.com/project-copacetic/copa-action/pull/29) in order to produce the *openvex report*.
However, it appears that targeting the main branch of the action (`uses: project-copacetic/copa-action@main`) does not yield the expected results, as the output openvex file is not produced.
Conversely, when targeting one of the test branches of @sozercan , it functions properly (`uses: sozercan/copa-action@out-vex`). 

This is the implicated section of our *patch* pipeline:  
```yaml
- name: Copa Action
  if: steps.vuln_count.outputs.vuln_count != '0'
  id: copa
  uses: sozercan/copa-action@out-vex.  # does not work with 'uses: project-copacetic/copa-action@main'
  with:
    image: ${{ matrix.images }}
    image-report: 'report.json'
    patched-tag: ${{ env.PATCHED_TAG }}
    output: ${{ env.PATCHED_TAG_SBOM }}-openvex-report.json

- name: Archive openvex vuln report
  uses: actions/upload-artifact@v4
  with:
    name: ${{ env.PATCHED_TAG_SBOM }}-openvex-report
    path: ${{ env.PATCHED_TAG_SBOM }}-openvex-report.json
```
